//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int ClaimID { get; set; }
        public string SentDate { get; set; }
        public string RecievedDate { get; set; }
        public string Phone { get; set; }
        public string ClinicCode { get; set; }
        public string ROI { get; set; }
        public int PatientID { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
