//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMRData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EMREntities : DbContext
    {
        public EMREntities()
            : base("name=EMREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
    
        public virtual ObjectResult<ShowPatient_Result> ShowPatient()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowPatient_Result>("ShowPatient");
        }
    }
}
