//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Claims = new HashSet<Claim>();
            this.Employers = new HashSet<Employer>();
            this.Providers = new HashSet<Provider>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int PatientID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string DOB { get; set; }
        public string MedicalRecordNumber { get; set; }
        public string Gender { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string Physician { get; set; }
        public string Gurrantor { get; set; }
        public string Spouse { get; set; }
        public string Father { get; set; }
        public string Mother { get; set; }
        public string EmergencyContact { get; set; }
        public string SecondaryName { get; set; }
        public string MaidenName { get; set; }
        public string Confidential { get; set; }
        public string MaritalStatus { get; set; }
        public string Smoker { get; set; }
        public string PrivacyNotice { get; set; }
        public string Military { get; set; }
        public string Race { get; set; }
        public string Religion { get; set; }
        public string Isolation { get; set; }
        public string BirthPlace { get; set; }
        public string Ethinicity { get; set; }
        public string Language { get; set; }
        public string Indigent { get; set; }
        public string DNR { get; set; }
        public string ExpiredDate { get; set; }
        public string PatientNote { get; set; }
        public string SocialInsuranceNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim> Claims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employer> Employers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
