//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int VisitID { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Service { get; set; }
        public string Balance { get; set; }
        public int PatientID { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
